version: '3.3'
services: 
  ui-e2e-dev:
    image: mat
    tty: true
    build: .
    container_name: cydev
    environment:
      - CYPRESS_DEV_USERNAME=${CYPRESS_DEV_USERNAME}
      - CYPRESS_DEV_PASSWORD=${CYPRESS_DEV_PASSWORD}
      - CYPRESS_DEV_ALT_USERNAME=${CYPRESS_DEV_ALT_USERNAME}
      - CYPRESS_DEV_ALT_PASSWORD=${CYPRESS_DEV_ALT_PASSWORD}
      - CYPRESS_TEST_USERNAME=${CYPRESS_TEST_USERNAME}
      - CYPRESS_TEST_PASSWORD=${CYPRESS_TEST_PASSWORD}
      - CYPRESS_TEST_ALT_USERNAME=${CYPRESS_TEST_ALT_USERNAME}
      - CYPRESS_TEST_ALT_PASSWORD=${CYPRESS_TEST_ALT_PASSWORD}
      - CYPRESS_VSAC_API_KEY=${CYPRESS_VSAC_API_KEY}
      - CYPRESS_DEVQDM56_DB_MONGO_GROUPID=${CYPRESS_DEVQDM56_DB_MONGO_GROUPID}
      - CYPRESS_DEVQDM55_DB_MONGO_GROUPID=${CYPRESS_DEVQDM55_DB_MONGO_GROUPID}
      - CYPRESS_DEVFHIR_DB_MONGO_GROUPID=${CYPRESS_DEVFHIR_DB_MONGO_GROUPID}
      - CYPRESS_MONGO_URL=${CYPRESS_MONGO_URL}
      - CYPRESS_MONGO_SSLCERT=${CYPRESS_MONGO_SSLCERT}
    volumes:
      - ./mochawesome-report:/app/mochawesome-report
