//Bonnie HARP Measure Details element definitions

export const measureDetailsParentDiv = '.measure-title'
export const measureDetailsCogWheel = '.settings-container'
export const inverseDangerButton = '.btn-danger-inverse'
export const deleteMeasureButton = '.delete-measure'
export const definitionsContainerDiv = '.panel-body'
export const initialPopulationCQL = '[data-define-name="Initial Population"]'
export const denominatorCQL = '[data-define-name="Denominator"]'
export const denominatorExclusionCQL = '[data-define-name="Denominator Exclusion"]'
export const numerator = '[data-define-name="Numerator"]'
export const flexibleSigmoidoscopyPerformedCQL = '[data-define-name="Flexible Sigmoidoscopy Performed"]'
export const ctColonographyPerformedCQL = '[data-define-name="CT Colonography Performed"]'
export const totalColectomyPerformedCQL = '[data-define-name="Total Colectomy Performed"]'
export const malignantNeoplasmEverCQL = '[data-define-name="Malignant Neoplasm Ever"]'
export const fecalOccultBloodTestPerformedCQL = '[data-define-name="Fecal Occult Blood Test Performed"]'
export const fecalImmunochemicalTestDNACQL = '[data-define-name="Fecal Immunochemical Test DNA"]'
export const colonoscopyPerformedCQL = '[data-define-name="Colonoscopy Performed"]'
export const hasHospiceCQL = '[data-define-name="Has Hospice"]'
export const qualifyingEncountersCQL = '[data-define-name="Qualifying Encounters"]'
export const functionsCQL = '#collapseview452-functions > .panel-body'
export const measuresHomePageBreadcrumb = '.breadcrumb > :nth-child(1) > a'